param(
    [string]$AgentId = "signet-vscode-custom-agent"
)

$ErrorActionPreference = "Stop"

$harnessName = "vscode-custom-agent"
$projectPath = (Get-Location).Path
$daemonUrl = "http://127.0.0.1:3850"
$generatedDir = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot "..\generated"))
$liveContextPath = Join-Path $generatedDir "signet-live-context.md"
$sessionStartContextPath = Join-Path $generatedDir "signet-session-start-context.md"
$promptRefreshStateDir = Join-Path $generatedDir "prompt-refresh-state"
$script:HookInputRaw = ($input | Out-String)

function Get-HookInputObject {
    $hookInput = $script:HookInputRaw

    if ([string]::IsNullOrWhiteSpace($hookInput) -and [Console]::IsInputRedirected) {
        $hookInput = [Console]::In.ReadToEnd()
    }

    if ([string]::IsNullOrWhiteSpace($hookInput)) {
        return @{}
    }

    try {
        $parsed = $hookInput | ConvertFrom-Json -Depth 10
        if ($null -eq $parsed) {
            return @{}
        }

        return $parsed
    }
    catch {
        return @{}
    }
}

function Write-GeneratedContextFile {
    param(
        [string]$Path,
        [string]$Inject,
        [string]$Source
    )

    New-Item -ItemType Directory -Path $generatedDir -Force | Out-Null

    $content = @(
        "<!-- Auto-generated by $Source. -->"
        ""
        $Inject.Trim()
        ""
    ) -join [Environment]::NewLine

    [System.IO.File]::WriteAllText($Path, $content, [System.Text.UTF8Encoding]::new($false))
}

function New-SignetAutoInjectPayload {
    param(
        [string]$Source,
        [string]$SessionKey,
        [string]$Inject
    )

    $payloadHeader = "[signet:auto-inject source={0} session_key={1} generated_at_utc={2}]" -f
        $Source,
        (Get-FirstNonEmptyValue -Values @($SessionKey) -Default "unknown"),
        [DateTime]::UtcNow.ToString("o")

    return @(
        $payloadHeader
        ""
        $Inject.Trim()
    ) -join [Environment]::NewLine
}

function New-SignetDebugSummary {
    param(
        [string]$Source,
        [string]$SessionKey,
        [string]$Inject,
        [string]$RoleDescription
    )

    $safeInject = if ($Inject) { $Inject } else { "" }
    $previewLine = (($safeInject -replace "\r?\n", " ").Trim())
    if ($previewLine.Length -gt 160) {
        $previewLine = $previewLine.Substring(0, 160) + "..."
    }

    return @(
        "# Signet Debug Snapshot"
        ""
        "- Debug only: true"
        ("- Role: {0}" -f $RoleDescription)
        ("- Source: {0}" -f $Source)
        ("- Session key: {0}" -f (Get-FirstNonEmptyValue -Values @($SessionKey) -Default "unknown"))
        ("- Generated at UTC: {0}" -f [DateTime]::UtcNow.ToString("o"))
        ("- Inject chars: {0}" -f $safeInject.Length)
        ("- Contains memory-feedback block: {0}" -f ($safeInject.Contains("<memory-feedback>")))
        ("- Preview: {0}" -f (Get-FirstNonEmptyValue -Values @($previewLine) -Default "<empty>"))
        ""
        "## Full Inject Payload"
        ""
        (Get-FirstNonEmptyValue -Values @($safeInject.Trim()) -Default "<empty>")
    ) -join [Environment]::NewLine
}

function Get-FirstNonEmptyValue {
    param(
        [object[]]$Values,
        [string]$Default = ""
    )

    foreach ($value in $Values) {
        if ($value -is [string] -and -not [string]::IsNullOrWhiteSpace($value)) {
            return $value
        }
    }

    return $Default
}

function Get-HookSessionKey {
    param(
        [object]$HookInput
    )

    return Get-FirstNonEmptyValue -Values @(
        $HookInput.sessionKey,
        $HookInput.sessionId,
        $HookInput.session_key,
        $HookInput.session_id
    )
}

function Get-SessionStatePath {
    param(
        [object]$HookInput,
        [string]$AgentIdentity
    )

    $sessionKey = Get-HookSessionKey -HookInput $HookInput
    $sessionIdentityParts = @(
        $AgentIdentity,
        $sessionKey
    ) | Where-Object { $_ -is [string] -and -not [string]::IsNullOrWhiteSpace($_) }

    $sessionIdentity = $sessionIdentityParts -join "|"
    if ([string]::IsNullOrWhiteSpace($sessionIdentity)) {
        $sessionIdentity = $AgentIdentity
    }

    $identityBytes = [System.Text.Encoding]::UTF8.GetBytes($sessionIdentity)
    $identityHash = [System.Convert]::ToHexString([System.Security.Cryptography.SHA256]::HashData($identityBytes)).ToLowerInvariant()
    return Join-Path $promptRefreshStateDir ("{0}.json" -f $identityHash)
}

function Initialize-PromptRefreshState {
    param(
        [string]$Path,
        [object]$HookInput,
        [string]$AgentIdentity
    )

    New-Item -ItemType Directory -Path $promptRefreshStateDir -Force | Out-Null

    $sessionKey = Get-HookSessionKey -HookInput $HookInput
    $state = @{
        agentId = $AgentIdentity
        sessionKey = $sessionKey
        sessionId = $sessionKey
        skipNextPromptRefresh = $true
        initializedAtUtc = [DateTime]::UtcNow.ToString("o")
    }

    [System.IO.File]::WriteAllText($Path, ($state | ConvertTo-Json -Depth 5) + [Environment]::NewLine, [System.Text.UTF8Encoding]::new($false))
}

$hookInput = Get-HookInputObject
$sessionStatePath = Get-SessionStatePath -HookInput $hookInput -AgentIdentity $AgentId

try {
    $sessionKey = Get-HookSessionKey -HookInput $hookInput
    $body = @{
        harness = $harnessName
        agentId = $AgentId
        project = $projectPath
    }

    if (-not [string]::IsNullOrWhiteSpace($sessionKey)) {
        $body.sessionKey = $sessionKey
        $body.sessionId = $sessionKey
    }

    if ($null -ne $hookInput.context) {
        $body.context = $hookInput.context
    }

    $response = Invoke-RestMethod -Method Post -Uri "$daemonUrl/api/hooks/session-start" -ContentType "application/json" -Body ($body | ConvertTo-Json -Depth 10) -TimeoutSec 5
    $inject = [string]$response.inject

    if ([string]::IsNullOrWhiteSpace($inject)) {
        $inject = "[signet] SessionStart hook returned no context."
    }
}
catch {
    $inject = "[signet] SessionStart hook failed for harness '$harnessName': $($_.Exception.Message)"
}

$sessionKey = Get-HookSessionKey -HookInput $hookInput
Write-GeneratedContextFile -Path $sessionStartContextPath -Inject (New-SignetDebugSummary -Source "SessionStart" -SessionKey $sessionKey -Inject $inject -RoleDescription "Diagnostic mirror of SessionStart injection. Agents must not read this file.") -Source "SessionStart"
Write-GeneratedContextFile -Path $liveContextPath -Inject (New-SignetDebugSummary -Source "SessionStart" -SessionKey $sessionKey -Inject "[signet] SessionStart completed. Live context is delivered through hook auto-injection." -RoleDescription "Diagnostic mirror of the live-context channel. Agents must not read this file.") -Source "SessionStart"
Initialize-PromptRefreshState -Path $sessionStatePath -HookInput $hookInput -AgentIdentity $AgentId

@{
    hookSpecificOutput = @{
        hookEventName = "SessionStart"
        additionalContext = (New-SignetAutoInjectPayload -Source "SessionStart" -SessionKey $sessionKey -Inject $inject)
    }
} | ConvertTo-Json -Depth 5

