param(
    [string]$AgentId = "signet-vscode-custom-agent"
)

$ErrorActionPreference = "Stop"

$harnessName = "vscode-custom-agent"
$projectPath = (Get-Location).Path
$daemonUrl = "http://127.0.0.1:3850"
$generatedDir = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot "..\generated"))
$liveContextPath = Join-Path $generatedDir "signet-live-context.md"
$sessionStartContextPath = Join-Path $generatedDir "signet-session-start-context.md"
$promptRefreshStateDir = Join-Path $generatedDir "prompt-refresh-state"
$script:HookInputRaw = ($input | Out-String)

function Get-HookInputObject {
    $hookInput = $script:HookInputRaw

    if ([string]::IsNullOrWhiteSpace($hookInput) -and [Console]::IsInputRedirected) {
        $hookInput = [Console]::In.ReadToEnd()
    }

    if ([string]::IsNullOrWhiteSpace($hookInput)) {
        return @{}
    }

    try {
        $parsed = $hookInput | ConvertFrom-Json -Depth 10
        if ($null -eq $parsed) {
            return @{}
        }

        return $parsed
    }
    catch {
        return @{}
    }
}

function Get-FirstNonEmptyValue {
    param(
        [object[]]$Values,
        [string]$Default = ""
    )

    foreach ($value in $Values) {
        if ($value -is [string] -and -not [string]::IsNullOrWhiteSpace($value)) {
            return $value
        }
    }

    return $Default
}

function Get-NormalizedSessionMetadata {
    param(
        [object]$HookInput
    )

    $sessionKey = Get-FirstNonEmptyValue -Values @(
        $HookInput.sessionKey,
        $HookInput.session_key
    )

    $sessionId = Get-FirstNonEmptyValue -Values @(
        $HookInput.sessionId,
        $HookInput.session_id,
        $sessionKey
    )

    return @{
        sessionKey = $sessionKey
        sessionId = $sessionId
    }
}

function Write-GeneratedContextFile {
    param(
        [string]$Path,
        [string]$Inject,
        [string]$Source
    )

    New-Item -ItemType Directory -Path $generatedDir -Force | Out-Null

    $content = @(
        "<!-- Auto-generated by $Source. -->"
        ""
        $Inject.Trim()
        ""
    ) -join [Environment]::NewLine

    [System.IO.File]::WriteAllText($Path, $content, [System.Text.UTF8Encoding]::new($false))
}

function Get-SessionStatePath {
    param(
        [object]$HookInput,
        [string]$AgentIdentity
    )

    $sessionIdentityParts = @(
        $AgentIdentity,
        $HookInput.sessionKey,
        $HookInput.sessionId
    ) | Where-Object { $_ -is [string] -and -not [string]::IsNullOrWhiteSpace($_) }

    $sessionIdentity = $sessionIdentityParts -join "|"
    if ([string]::IsNullOrWhiteSpace($sessionIdentity)) {
        $sessionIdentity = $AgentIdentity
    }

    $identityBytes = [System.Text.Encoding]::UTF8.GetBytes($sessionIdentity)
    $identityHash = [System.Convert]::ToHexString([System.Security.Cryptography.SHA256]::HashData($identityBytes)).ToLowerInvariant()
    return Join-Path $promptRefreshStateDir ("{0}.json" -f $identityHash)
}

function Initialize-PromptRefreshState {
    param(
        [string]$Path,
        [object]$HookInput,
        [string]$AgentIdentity
    )

    New-Item -ItemType Directory -Path $promptRefreshStateDir -Force | Out-Null

    $state = @{
        agentId = $AgentIdentity
        sessionKey = $HookInput.sessionKey
        sessionId = $HookInput.sessionId
        skipNextPromptRefresh = $true
        initializedAtUtc = [DateTime]::UtcNow.ToString("o")
    }

    [System.IO.File]::WriteAllText($Path, ($state | ConvertTo-Json -Depth 5) + [Environment]::NewLine, [System.Text.UTF8Encoding]::new($false))
}

$hookInput = Get-HookInputObject
$sessionMetadata = Get-NormalizedSessionMetadata -HookInput $hookInput
$sessionStatePath = Get-SessionStatePath -HookInput $hookInput -AgentIdentity $AgentId

try {
    $body = @{
        harness = $harnessName
        agentId = $AgentId
        projectPath = $projectPath
    }

    if (-not [string]::IsNullOrWhiteSpace($sessionMetadata.sessionKey)) {
        $body.sessionKey = $sessionMetadata.sessionKey
    }

    if (-not [string]::IsNullOrWhiteSpace($sessionMetadata.sessionId)) {
        $body.sessionId = $sessionMetadata.sessionId
    }

    if ($null -ne $hookInput.context) {
        $body.context = $hookInput.context
    }

    $response = Invoke-RestMethod -Method Post -Uri "$daemonUrl/api/hooks/session-start" -ContentType "application/json" -Body ($body | ConvertTo-Json -Depth 10) -TimeoutSec 5
    $inject = [string]$response.inject

    if ([string]::IsNullOrWhiteSpace($inject)) {
        $inject = "[signet] SessionStart hook returned no context."
    }
}
catch {
    $inject = "[signet] SessionStart hook failed for harness '$harnessName': $($_.Exception.Message)"
}

Write-GeneratedContextFile -Path $sessionStartContextPath -Inject $inject -Source "SessionStart"
Write-GeneratedContextFile -Path $liveContextPath -Inject "[signet] SessionStart completed. Live context activates on the second user prompt." -Source "SessionStart"
Initialize-PromptRefreshState -Path $sessionStatePath -HookInput (@{ sessionKey = $sessionMetadata.sessionKey; sessionId = $sessionMetadata.sessionId }) -AgentIdentity $AgentId

@{
    hookSpecificOutput = @{
        hookEventName = "SessionStart"
        additionalContext = $inject.Trim()
    }
} | ConvertTo-Json -Depth 5

