param(
    [string]$AgentId = "signet-vscode-custom-agent"
)

$ErrorActionPreference = "Stop"

$harnessName = "vscode-custom-agent"
$projectPath = (Get-Location).Path
$daemonUrl = "http://127.0.0.1:3850"
$generatedDir = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot "..\generated"))
$liveContextPath = Join-Path $generatedDir "signet-live-context.md"
$debugInputPath = Join-Path $generatedDir "signet-last-user-prompt-input.json"
$promptRefreshStateDir = Join-Path $generatedDir "prompt-refresh-state"
$script:HookInputRaw = ($input | Out-String)

function Get-HookInputObject {
    $hookInput = $script:HookInputRaw

    if ([string]::IsNullOrWhiteSpace($hookInput) -and [Console]::IsInputRedirected) {
        $hookInput = [Console]::In.ReadToEnd()
    }

    if ([string]::IsNullOrWhiteSpace($hookInput)) {
        return @{}
    }

    try {
        $parsed = $hookInput | ConvertFrom-Json -Depth 10
        if ($null -eq $parsed) {
            return @{}
        }

        return $parsed
    }
    catch {
        return @{}
    }
}

function Get-NormalizedSessionMetadata {
    param(
        [object]$HookInput
    )

    $sessionKey = Get-FirstNonEmptyValue -Values @(
        $HookInput.sessionKey,
        $HookInput.session_key
    )

    $sessionId = Get-FirstNonEmptyValue -Values @(
        $HookInput.sessionId,
        $HookInput.session_id,
        $sessionKey
    )

    return @{
        sessionKey = $sessionKey
        sessionId = $sessionId
    }
}

function Write-LiveContextFile {
    param(
        [string]$Inject,
        [string]$Source
    )

    New-Item -ItemType Directory -Path $generatedDir -Force | Out-Null

    $content = @(
        "<!-- Auto-generated by $Source. -->"
        ""
        $Inject.Trim()
        ""
    ) -join [Environment]::NewLine

    [System.IO.File]::WriteAllText($liveContextPath, $content, [System.Text.UTF8Encoding]::new($false))
}

function Write-DebugInputFile {
    param(
        [object]$HookInput
    )

    New-Item -ItemType Directory -Path $generatedDir -Force | Out-Null
    $json = $HookInput | ConvertTo-Json -Depth 20
    [System.IO.File]::WriteAllText($debugInputPath, $json + [Environment]::NewLine, [System.Text.UTF8Encoding]::new($false))
}

function Get-FirstNonEmptyValue {
    param(
        [object[]]$Values,
        [string]$Default = ""
    )

    foreach ($value in $Values) {
        if ($value -is [string] -and -not [string]::IsNullOrWhiteSpace($value)) {
            return $value
        }
    }

    return $Default
}

function Get-SessionStatePath {
    param(
        [object]$HookInput,
        [string]$AgentIdentity
    )

    $sessionIdentityParts = @(
        $AgentIdentity,
        $HookInput.sessionKey,
        $HookInput.sessionId
    ) | Where-Object { $_ -is [string] -and -not [string]::IsNullOrWhiteSpace($_) }

    $sessionIdentity = $sessionIdentityParts -join "|"
    if ([string]::IsNullOrWhiteSpace($sessionIdentity)) {
        $sessionIdentity = $AgentIdentity
    }

    $identityBytes = [System.Text.Encoding]::UTF8.GetBytes($sessionIdentity)
    $identityHash = [System.Convert]::ToHexString([System.Security.Cryptography.SHA256]::HashData($identityBytes)).ToLowerInvariant()
    return Join-Path $promptRefreshStateDir ("{0}.json" -f $identityHash)
}

function Consume-InitialPromptRefreshSkip {
    param(
        [string]$Path
    )

    if (-not (Test-Path $Path)) {
        return $false
    }

    Remove-Item -Path $Path -Force -ErrorAction SilentlyContinue
    return $true
}

try {
    $hookInput = Get-HookInputObject
    $sessionMetadata = Get-NormalizedSessionMetadata -HookInput $hookInput
    Write-DebugInputFile -HookInput $hookInput
    $sessionStatePath = Get-SessionStatePath -HookInput (@{ sessionKey = $sessionMetadata.sessionKey; sessionId = $sessionMetadata.sessionId }) -AgentIdentity $AgentId

    if (Consume-InitialPromptRefreshSkip -Path $sessionStatePath) {
        @{
            continue = $true
        } | ConvertTo-Json -Depth 3
        return
    }

    $userPrompt = Get-FirstNonEmptyValue -Values @(
        $hookInput.promptText,
        $hookInput.userPrompt,
        $hookInput.userMessage,
        $hookInput.prompt,
        $hookInput.message,
        $hookInput.text,
        $hookInput.input,
        $hookInput.chatSessionInput,
        $hookInput.request,
        $hookInput.user_input
    ) -Default "[signet] VS Code custom-agent prompt hook fired without prompt text."

    if ($userPrompt -isnot [string] -and $null -ne $userPrompt) {
        $userPrompt = $userPrompt.ToString()
    }

    $body = @{
        harness = $harnessName
        agentId = $AgentId
        cwd = $projectPath
        userPrompt = $userPrompt
    }

    if (-not [string]::IsNullOrWhiteSpace($sessionMetadata.sessionKey)) {
        $body.sessionKey = $sessionMetadata.sessionKey
    }

    if (-not [string]::IsNullOrWhiteSpace($sessionMetadata.sessionId)) {
        $body.sessionId = $sessionMetadata.sessionId
    }

    if ($null -ne $hookInput.lastAssistantMessage) {
        $body.lastAssistantMessage = $hookInput.lastAssistantMessage
    }

    $response = Invoke-RestMethod -Method Post -Uri "$daemonUrl/api/hooks/user-prompt-submit" -ContentType "application/json" -Body ($body | ConvertTo-Json -Depth 10) -TimeoutSec 5
    $inject = [string]$response.inject

    if ([string]::IsNullOrWhiteSpace($inject)) {
        $inject = "[signet] UserPromptSubmit hook returned no context."
    }

    Write-LiveContextFile -Inject $inject -Source "UserPromptSubmit"
}
catch {
    $inject = "[signet] UserPromptSubmit hook failed for harness '$harnessName': $($_.Exception.Message)"
    Write-LiveContextFile -Inject $inject -Source "UserPromptSubmit"
}

@{
    continue = $true
} | ConvertTo-Json -Depth 3
